---
# Ansible Collection Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: awx.awx
    version: ">=24.0.0"
  - name: community.general
    version: ">=8.0.0"
  - name: community.vmware
    version: ">=3.0.0"


